# Generated by Django 3.2.1 on 2021-05-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_demodate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demodate',
            name='demodate',
            field=models.DateTimeField(),
        ),
    ]
