# Generated by Django 3.2.1 on 2021-05-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_alter_demodate_demodate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travels', models.CharField(max_length=50)),
                ('departure_timeHours', models.IntegerField()),
                ('departure_timeMinutes', models.IntegerField()),
                ('departure_palce', models.CharField(max_length=50)),
                ('arrival_timeHours', models.IntegerField()),
                ('arrival_timeMinutes', models.IntegerField()),
                ('arrival_place', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=25)),
                ('fare', models.CharField(max_length=20)),
                ('seats_available', models.IntegerField()),
                ('ac_sleeper', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'buses_table',
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(max_length=50)),
                ('departure_timeHours', models.IntegerField()),
                ('departure_timeMinutes', models.IntegerField()),
                ('departure_palce', models.CharField(max_length=50)),
                ('arrival_timeHours', models.IntegerField()),
                ('arrival_timeMinutes', models.IntegerField()),
                ('arrival_place', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=25)),
                ('fare', models.CharField(max_length=20)),
                ('seats_available', models.IntegerField()),
            ],
            options={
                'db_table': 'flights_table',
            },
        ),
    ]
