# Generated by Django 3.2.1 on 2021-05-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_buses_flights'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='bus_num',
            field=models.CharField(default='AP04BN5444', max_length=15),
        ),
    ]
