# Generated by Django 3.1.7 on 2021-05-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_auto_20210516_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='one',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
    ]
