# Generated by Django 3.1.7 on 2021-05-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0011_buses_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='eight',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='buses',
            name='elven',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='buses',
            name='five',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='buses',
            name='fivethn',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='buses',
            name='four',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='buses',
            name='fouthn',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='buses',
            name='nine',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='buses',
            name='seven',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='buses',
            name='six',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='buses',
            name='sixthn',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='buses',
            name='ten',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='buses',
            name='thirtn',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='buses',
            name='three',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='buses',
            name='twelve',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='buses',
            name='two',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
    ]
