# Generated by Django 3.2.1 on 2021-05-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0013_tours'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('population', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'touristsData_table',
            },
        ),
    ]
