# Generated by Django 3.2.1 on 2021-05-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0016_auto_20210518_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buses',
            old_name='arrivalplace',
            new_name='arrival_place',
        ),
        migrations.RenameField(
            model_name='buses',
            old_name='departurepalce',
            new_name='departure_palce',
        ),
    ]
