# Generated by Django 3.2.1 on 2021-05-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0017_auto_20210518_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='ac_sleeper',
            field=models.CharField(max_length=20),
        ),
    ]
