# Generated by Django 3.2.1 on 2021-05-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0020_touristplaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplaces',
            name='state',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
