# Generated by Django 3.2.1 on 2021-05-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0021_touristplaces_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromplace', models.CharField(max_length=100)),
                ('toplace', models.CharField(max_length=100)),
                ('distance', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'distances',
            },
        ),
    ]
